# Generated by Django 4.0.5 on 2022-07-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='decription',
            new_name='decripcion',
        ),
    ]
