# Generated by Django 4.0.4 on 2022-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0003_rename_decripcion_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
