# Generated by Django 4.0.4 on 2022-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0008_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='apellido',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.EmailField(default=11, max_length=400, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.IntegerField(default=1, verbose_name='Telefono de contacto'),
            preserve_default=False,
        ),
    ]
