# Generated by Django 4.0.5 on 2022-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0009_registro_apellido_registro_email_registro_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='APELLIDO'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-MAIL'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='NOMBRE'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.IntegerField(verbose_name='TELEFONO DE CONTACTO'),
        ),
    ]
