# Generated by Django 4.0.4 on 2022-07-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0010_alter_registro_apellido_alter_registro_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE')),
                ('apellido', models.CharField(max_length=100, verbose_name='APELLIDO')),
                ('telefono', models.IntegerField(verbose_name='TELEFONO DE CONTACTO')),
                ('email', models.EmailField(max_length=254, verbose_name='E-MAIL')),
            ],
        ),
    ]
