# Generated by Django 4.0.5 on 2022-07-25 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 25, 22, 29, 40, 507066, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
