# Generated by Django 4.0.4 on 2022-07-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0011_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='about',
            name='telefono',
        ),
    ]
