# Generated by Django 4.0.4 on 2022-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0012_remove_about_apellido_remove_about_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
            ],
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
