# Generated by Django 4.0.5 on 2022-07-25 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0015_alter_consulta_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 25, 23, 16, 22, 186194, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
