# Generated by Django 4.0.5 on 2022-07-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0016_libro_fecha_alter_consulta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Imagen'),
        ),
    ]
