# Generated by Django 4.0.5 on 2022-07-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0017_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
