# Generated by Django 4.0.4 on 2022-08-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedio', '0018_alter_libro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='mensaje',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia']], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha',
            field=models.DateField(blank=True, verbose_name='Fecha (AAAA-MM-DD)'),
        ),
    ]
